Update gameConsole.ts for JELOS directory support
emmercm/igir pull request #698
Opened 2023-09-25 02:16 UTC by samwelnella

Updates gameConsole.ts, argumentsParser.ts and outputFactory.ts to add a {jelos} output token to support JELOS' directory structure

2023-09-26 00:19 UTC, emmercm requested changes

2023-09-26 00:19 UTC, emmercm commented on src/types/outputFactory.ts
> +    const jelos = gameConsole.getJelos();
This is great work! I spot-checked a number of the values and they look right. One last step, could you add some unit tests for this in `outputFactory.test.ts`? There are some other examples in there that you can copy.

2023-09-26 13:41 UTC, samwelnella commented
Hi, I've added new tests in `outputFactory.test.ts` for `{jelos}` based on the `{batocera}` tests

2023-09-27 00:22 UTC, emmercm approved these changes

2023-09-27 01:55 UTC, emmercm commented
Hi @samwelnella, looks like there are some syntax errors reported by CI.

2023-10-05 01:17 UTC, samwelnella commented
I think I fixed the issue but some tests have been stuck with "Expected" status for a while. I'm not sure what to do.

2023-10-05 04:57 UTC, emmercm commented
Hi @samwelnella, it's entirely a GitHub security setting that doesn't have fine-grained control. Users that aren't marked as repository collaborators can't initiate some workflows, to prevent secrets from being exported by malicious actors. I'll make sure the tests get triggered.

2023-10-05 05:30 UTC, emmercm commented
@samwelnella I'm fighting some unit tests that keep failing in macOS, I'm going to need to debug. I think there's a potential bug being caused by https://github.com/emmercm/igir/pull/630.

2023-10-06 00:04 UTC, merged