Add New Outputs (EmulationStation + RetroDECK)
emmercm/igir pull request #943
Opened 2024-02-21 02:10 UTC by maxexcloo

2024-02-21 16:44 UTC, emmercm requested changes

2024-02-21 22:30 UTC, maxexcloo commented on src/types/gameConsole.ts
> +    new GameConsole(/CPC/i, ['.cdt', '.cpr', '.dsk', '.kcr', '.m3u', '.sna', '.tap', '.tar', '.voc'], {
Will revert any that aren’t unique - but what if the extensions are the same between consoles? MSX and MSX2 for example?

2024-02-21 22:30 UTC, maxexcloo commented on src/types/outputFactory.ts
> +      output = output.replace('{emulationstation}', emulationstation);
Will do!

2024-02-21 22:31 UTC, maxexcloo commented on src/modules/argumentsParser.ts
> +    {emulationstation} The ROM's emulator-specific /roms/* directory for the 'EmulationStation' image (e.g. "gb")
How about ES-DE? I’ve seen that abbreviation before - I totally agree on the width btw

2024-02-22 00:52 UTC, maxexcloo commented
@emmercm have updated and incorporated your feedback - let me know if there's anything else I'm missing :)

2024-02-24 02:46 UTC, emmercm commented on src/modules/argumentsParser.ts
> +    {emulationstation} The ROM's emulator-specific /roms/* directory for the 'EmulationStation' image (e.g. "gb")
I'm great with `{es}`!

2024-02-24 02:58 UTC, emmercm commented
@maxexcloo thank you for addressing everything! I made a few small changes so that I can include this in tonight's release: https://github.com/emmercm/igir/pull/943/files/e4b29c8e8329154a264fa15dc6aa5cb7d9480c3f..7d3cf4c9725c223a2e5fdd9354ce412bde6345e4

2024-02-24 03:20 UTC, maxexcloo commented
Apologies for the errors there, appreciate the extra pair of eyes and the help merging this 💯

2024-02-24 03:40 UTC, merged